export const LIST_ACTION_TYPES = {
  FETCH_LIST_START: "list/SET_LIST_START",
  FETCH_LIST_SUCCESS: "list/FETCH_LIST_SUCCESS",
  FETCH_LIST_FAILED: "list/FETCH_LIST_FAILED",
  SET_SEARCH_STRING: "/list/SET_SEARCH_STRING",
};