export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: "user/SET_CURRENT_USER",
  FETCH_SETTINGS_START: "user/FETCH_SETTINGS_START",
  FETCH_SETTINGS_SUCCESS: "user/FETCH_SETTINGS_SUCCESS",
  FETCH_SETTINGS_FAILED: "user/FETCH_SETTINGS_FAILED",
};